// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu5Y7daf-mOs2zaQCx2FTsK6-hm2rNkOg',
    appId: '1:345858558847:web:944e189ea431db207ea84a',
    messagingSenderId: '345858558847',
    projectId: 'dreamtier-app',
    authDomain: 'dreamtier-app.firebaseapp.com',
    storageBucket: 'dreamtier-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeWJ-PPKaWaOpMhD4yCi6G3WAYlrreK54',
    appId: '1:345858558847:android:5b9b754c0d45e26e7ea84a',
    messagingSenderId: '345858558847',
    projectId: 'dreamtier-app',
    storageBucket: 'dreamtier-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATHPE2DzNOp3kjEX_BLJRRSWvoLD3D1bw',
    appId: '1:345858558847:ios:a413b0b60a705f3c7ea84a',
    messagingSenderId: '345858558847',
    projectId: 'dreamtier-app',
    storageBucket: 'dreamtier-app.appspot.com',
    iosBundleId: 'com.dreamtier.dreamtier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATHPE2DzNOp3kjEX_BLJRRSWvoLD3D1bw',
    appId: '1:345858558847:ios:5ef4407867a448397ea84a',
    messagingSenderId: '345858558847',
    projectId: 'dreamtier-app',
    storageBucket: 'dreamtier-app.appspot.com',
    iosBundleId: 'com.dreamtier.dreamtier.RunnerTests',
  );
}
